---
- name: Restart promtail
  become: True
  systemd:
    name: "{{ promtail_systemd_service }}"
    state: restarted
    daemon_reload: True
  tags:
    - promtail_run
    - promtail

- name: daemon-reload
  command: systemctl daemon-reload

- name: node_exporter_start
  command: systemctl restart node_exporter