--- 
- name: Install required package
  apt:
    name:
      - curl 
      - gnupg2 
      - ca-certificates 
      - lsb-release 
      - ubuntu-keyring
    state: present 

- name: Import singing key
  shell: curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor |  tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null

- name: Add apt repository
  shell: echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu `lsb_release -cs` nginx" |  tee /etc/apt/sources.list.d/nginx.list

- name: Install nginx
  apt:
    name:
      - nginx
    update_cache: yes