---
- name: Ensure netplan is installed 
  apt: 
    name: 
      - "netplan.io"
      - "netplan-generator"
      - "network-manager"
    state: present
    update_cache: false
  
# Create ansible template
- name: Backup netplan config file 
  archive:
    path: "{{ netplan_conf_path }}/netplan.yaml"
    dest: /etc/netplan/netplan.tar.gz
    format: gz
  ignore_errors: true

- name: Find all *.yaml files
  command: find "{{ netplan_conf_path }}" -name "*.yaml"
  register: yaml_files

- name: Remove YAML files
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ yaml_files.stdout_lines }}"

- name: Generate Netplan configuration
  template:
    dest: /etc/netplan/netplan.yaml
    src: netplan.j2
    mode: 0644

  with_items: "{{ interfaces }}"
  notify: 
    - "netplan_apply"
