---
# tasks file for kubernetes
- import_tasks: dependency.yml
  tags: kube_dependencies

- import_tasks: master.yml
  tags: kube_master

- import_tasks: worker.yml
  tags: kube_worker

- import_tasks: network.yml
  tags: init_networking